version: 2
jobs:
  generate_cache:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "front/Dockerfile" }}
          paths: ~/caches/images.tar
      - run:
          name: Check cache file, if not exists then pull images and generate cache.
          command: |
            if [ ! -f ~/caches/images.tar ]; then
              docker-compose -f docker-compose.yml pull
              docker-compose -f docker-compose.yml build
              mkdir -p ~/caches
              docker save $(docker images | awk 'NR>=2 && ! /^<none>/{print $1}') -o ~/caches/images.tar
            fi
      - save_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "front/Dockerfile" }}
          paths: ~/caches/images.tar
      - run:
          name: finish cacheing
          command: echo "finish cache"

  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum ".circleci/config.yml" }}-{{ checksum "docker-compose.yml" }}-{{ checksum "front/Dockerfile" }}
          paths: ~/caches/images.tar
      - run: 
          name: docker load
          command: if test -d ~/caches; then docker load -i ~/caches/images.tar; fi
      - run:
          name: Build Docker Image
          command: docker-compose -f docker-compose.yml build
      - run:
            name: docker-compose up
            command: |
                 docker-compose -f docker-compose.yml up -d
      - run:
            name: finish build
            command: echo "finish build"

  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b5:2e:ca:82:be:ed:bc:97:e8:c5:87:16:43:75:f9:12"
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -p 22222 "cd /var/reiwa_bustimer && git pull origin master && docker-compose build --no-cache && docker-compose up -d"
      - run:
          name: Exit from SSH
          command: exit
      - run:
          name: finish deploy
          command: echo "finish deploy"


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - generate_cache
      - build:
          requires:
            - generate_cache
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
